### ISSUE TITLE
Añadir función->Bot bloqueado

### ISSUE THREAD

**Issue by jooonni** [4nt0n10M4/freedompop-bot#5]
Estaría bien tener un comando con el cual se pudiera ver el número de personas que han bloqueado el bot.

**Comment by 4nt0n10M4** [comment]
Buena idea, ahora mismo lo pongo, sería algo así:
![image](https://user-images.githubusercontent.com/29716718/33904101-cc142124-df7a-11e7-902e-05210b203d9d.png)

**Comment by 4nt0n10M4** [comment]
Añadido, aqui tienes el commit:
https://github.com/4nt0n10M4/freedompop-bot/commit/6f794fd85b6a68950903f8285a4c64ce1a05c2cd *Añadida función de /bloqueado*
_Ahora podrás saber el numero de usuarios que ha bloqueado al bot._

**Comment by 4nt0n10M4** [comment]
Añadido, aqui tienes el commit:
https://github.com/4nt0n10M4/freedompop-bot/commit/6f794fd85b6a68950903f8285a4c64ce1a05c2cd *Añadida función de /bloqueado*
_Ahora podrás saber el numero de usuarios que ha bloqueado al bot._
